/**
 * =============================================================================
 *  Prospección B2B — fixtures del proveedor SIMULADO
 * -----------------------------------------------------------------------------
 *  Negocios de ejemplo con datos REALISTAS de la Quinta Región:
 *  comunas reales, categorías reales, nombres chilenos.
 *  Son datos SINTÉTICOS (no scrapeados): solo para modo simulación/demo.
 *  En producción, el descubrimiento real debe venir de fuentes con
 *  términos de uso validados (ver scraper.js — deshabilitado por defecto).
 * =============================================================================
 */

export const SIMULATED_BUSINESSES = [
  {
    name: 'Fuente Alemana Viña',
    category: 'restaurantes',
    commune: 'Viña del Mar',
    address: 'Av. San Martín 850, Viña del Mar',
    lat: -33.0312, lon: -71.5365,
    email: 'contacto@fuentealemana.cl',
    phone: '+56322951234',
    website: null,
    rating: 4.4, reviewCount: 210,
    instagram: '@fuentealemanavina',
    facebook: 'fuentealemanavina',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 10:00-22:00',
  },
  {
    name: 'Café del Mar Viña',
    category: 'cafeterias',
    commune: 'Viña del Mar',
    address: 'Av. Perú 330, Viña del Mar',
    lat: -33.0192, lon: -71.5528,
    email: 'hola@cafedelmar.cl',
    phone: '+56966778899',
    website: 'https://cafedelmar.cl',
    rating: 4.6, reviewCount: 64,
    instagram: '@cafedelmarvina',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 7:30-21:00',
  },
  {
    name: 'Restaurante El Vergel',
    category: 'restaurantes',
    commune: 'Viña del Mar',
    address: 'Calle 1 Norte 412, Viña del Mar',
    lat: -33.0120, lon: -71.5551,
    email: 'mesa@elvergel.cl',
    phone: '+56322945678',
    website: null,
    rating: 3.9, reviewCount: 28,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Mar-Dom 12:00-16:00, 19:00-23:00',
  },
  {
    name: 'Dental Sonrisa Viña',
    category: 'salud_privada',
    commune: 'Viña del Mar',
    address: 'Av. Libertad 1234, Viña del Mar',
    lat: -33.0246, lon: -71.5518,
    email: 'contacto@dentallsonrisa.cl',
    phone: '+56322981234',
    website: 'https://dentallsonrisa.cl',
    rating: 3.8, reviewCount: 42,
    instagram: '@dentallsonrisa',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 9:00-18:00',
  },
  {
    name: 'Café del Puerto',
    category: 'cafeterias',
    commune: 'Valparaíso',
    address: 'Calle Prat 456, Valparaíso',
    lat: -33.0458, lon: -71.6197,
    email: 'hola@cafedelpuerto.cl',
    phone: '+56987654321',
    website: 'https://cafedelpuerto.cl',
    rating: 4.5, reviewCount: 18,
    instagram: '@cafedelpuertovpo',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 8:00-21:00',
  },
  {
    name: 'Gimnasio IronQuilpué',
    category: 'gimnasios',
    commune: 'Quilpué',
    address: 'Av. Aníbal Pinto 789, Quilpué',
    lat: -33.0473, lon: -71.4428,
    email: 'info@ironquilpue.cl',
    phone: '+56912345678',
    website: null,
    rating: 4.1, reviewCount: 9,
    instagram: '@ironquilpue',
    verifiedSignal: 'Instagram',
    hours: 'Lun-Sab 7:00-22:00',
  },
  {
    name: 'Hostal Canela Concon',
    category: 'alojamiento_turismo',
    commune: 'Concón',
    address: 'Av. Borgoño 1500, Concón',
    lat: -32.9175, lon: -71.5310,
    email: null,
    phone: '+56998765432',
    website: 'https://hostalcanela.cl',
    rating: 3.5, reviewCount: 27,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Recepción 24h',
  },
  {
    name: 'AutoMecánica El Bosque',
    category: 'automotor',
    commune: 'Villa Alemana',
    address: 'Av. Las Acacias 321, Villa Alemana',
    lat: -32.9336, lon: -71.3750,
    email: 'contacto@automecanicaelbosque.cl',
    phone: '+56955667788',
    website: null,
    rating: null, reviewCount: 0,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 8:30-18:30',
  },
  {
    name: 'Panadería La Espiga',
    category: 'restaurantes',
    commune: 'Quillota',
    address: 'Calle O\'Higgins 210, Quillota',
    lat: -32.8833, lon: -71.2500,
    email: null,
    phone: '+56334455667',
    website: null,
    rating: 4.7, reviewCount: 3,
    instagram: '@laespigaquillota',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 7:00-20:00',
  },
  {
    name: 'Clínica Veterinaria Patitas',
    category: 'salud_privada',
    commune: 'Limache',
    address: 'Av. Matta 100, Limache',
    lat: -32.9667, lon: -71.2667,
    email: 'atencion@patitasvet.cl',
    phone: '+56911223344',
    website: 'https://patitasvet.cl',
    rating: 4.2, reviewCount: 61,
    instagram: '@patitasvet',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Sab 9:00-19:00',
  },
  {
    name: 'Boutique Luna Nueva',
    category: 'retail',
    commune: 'San Antonio',
    address: 'Av. Barros Luco 55, San Antonio',
    lat: -33.5955, lon: -71.6130,
    email: 'ventas@lunanueva.cl',
    phone: '+56922334455',
    website: null,
    rating: 3.9, reviewCount: 14,
    instagram: '@lunanuevasanantonio',
    verifiedSignal: 'Instagram',
    hours: 'Lun-Sab 10:00-19:00',
  },
  {
    name: 'Constructora Andes Sur',
    category: 'construccion',
    commune: 'San Felipe',
    address: 'Av. Libertador 880, San Felipe',
    lat: -32.7500, lon: -70.7333,
    email: 'proyectos@andessur.cl',
    phone: '+56966778899',
    website: 'https://andessur.cl',
    rating: null, reviewCount: 0,
    instagram: null,
    verifiedSignal: 'LinkedIn',
    hours: 'Lun-Vie 8:00-17:00',
  },
  {
    name: 'Escuela de Danza Ritmo',
    category: 'educacion',
    commune: 'Valparaíso',
    address: 'Calle Condell 990, Valparaíso',
    lat: -33.0370, lon: -71.6230,
    email: 'inscripciones@danzaritmo.cl',
    phone: '+56944556677',
    website: 'https://danzaritmo.cl',
    rating: 4.8, reviewCount: 22,
    instagram: '@danzaritmovpo',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 15:00-21:00',
  },
  {
    name: 'Asesorías Contables Pérez',
    category: 'servicios_profesionales',
    commune: 'Viña del Mar',
    address: 'Av. Perú 1100, Viña del Mar',
    lat: -33.0190, lon: -71.5480,
    email: 'contacto@perezcontadores.cl',
    phone: '+56988776655',
    website: null,
    rating: 4.0, reviewCount: 7,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 9:00-18:00',
  },
  {
    name: 'Cervecería Artesanal Muelle',
    category: 'bares',
    commune: 'Valparaíso',
    address: 'Paseo 21 de Mayo 200, Valparaíso',
    lat: -33.0385, lon: -71.6270,
    email: null,
    phone: '+56933445566',
    website: 'https://cerveceriamuelle.cl',
    rating: 4.3, reviewCount: 150,
    instagram: '@cerveceriamuelle',
    facebook: 'cerveceriamuelle',
    verifiedSignal: 'Google Maps',
    hours: 'Mar-Dom 12:00-24:00',
  },
];

// --- FIXTURES EXPANDIDOS (datos sintéticos de la Quinta Región) ---
export const SIMULATED_BUSINESSES_EXTRA = [
  {'name': 'Fuente El Sabor', 'category': 'restaurantes', 'commune': 'Valparaíso', 'address': 'Av. Argentina 50, Valparaíso', 'lat': -33.0302, 'lon': -71.6423, 'email': 'contacto@fuenteelsabor.cl', 'phone': '+56945501229', 'website': 'https://www.fuenteelsabor.cl', 'rating': 4.5, 'reviewCount': 120, 'instagram': '@fuenteelsabor', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Restaurante La Picá', 'category': 'restaurantes', 'commune': 'Viña del Mar', 'address': 'Av. Perú 87, Viña del Mar', 'lat': -33.0151, 'lon': -71.5447, 'email': null, 'phone': '+56327047912', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Asados Don Carlos', 'category': 'restaurantes', 'commune': 'Quilpué', 'address': 'Av. Los Carrera 124, Quilpué', 'lat': -33.066, 'lon': -71.4591, 'email': 'info@asadosdoncarlos.cl', 'phone': null, 'website': null, 'rating': 3.9, 'reviewCount': 28, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Pescados y Mariscos El Malecón', 'category': 'restaurantes', 'commune': 'Villa Alemana', 'address': 'Av. San Alberto Hurtado 161, Villa Alemana', 'lat': -32.9443, 'lon': -71.3709, 'email': null, 'phone': '+56981425794', 'website': null, 'rating': 4.7, 'reviewCount': 200, 'instagram': '@pescadosymariscoselm', 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Fuente Los Amigos', 'category': 'restaurantes', 'commune': 'Concón', 'address': 'Av. Costanera 198, Concón', 'lat': -32.9207, 'lon': -71.533, 'email': 'ventas@fuentelosamigos.cl', 'phone': '+56338773615', 'website': 'https://fuentelosamigos.cl', 'rating': 3.5, 'reviewCount': 12, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Completos El Rancho', 'category': 'restaurantes', 'commune': 'Limache', 'address': 'Calle Los Carrera 235, Limache', 'lat': -32.958800000000004, 'lon': -71.2731, 'email': 'hola@completoselrancho.cl', 'phone': '+56929452751', 'website': null, 'rating': 4.0, 'reviewCount': 67, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Pizzería Nápoles', 'category': 'restaurantes', 'commune': 'Quillota', 'address': 'Calle Balmaceda 272, Quillota', 'lat': -32.8992, 'lon': -71.2548, 'email': null, 'phone': '+56327185333', 'website': null, 'rating': null, 'reviewCount': 0, 'instagram': '@pizzerianapoles', 'verifiedSignal': 'Instagram', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Restaurante La Parrilla', 'category': 'restaurantes', 'commune': 'San Antonio', 'address': 'Calle Las Gaviotas 309, San Antonio', 'lat': -33.5832, 'lon': -71.60379999999999, 'email': 'contacto@restaurantelaparrill.cl', 'phone': null, 'website': 'https://www.restaurantelaparrill.cl', 'rating': 4.3, 'reviewCount': 89, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Sushi Maki', 'category': 'restaurantes', 'commune': 'Casablanca', 'address': 'Calle Yungay 346, Casablanca', 'lat': -33.3153, 'lon': -71.3978, 'email': null, 'phone': '+56958229128', 'website': 'https://www.sushimaki.cl', 'rating': 3.8, 'reviewCount': 5, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Fuentes Donde Julio', 'category': 'restaurantes', 'commune': 'Quintero', 'address': 'Calle El Cangrejo 383, Quintero', 'lat': -32.7535, 'lon': -71.5286, 'email': 'info@fuentesdondejulio.cl', 'phone': '+56338212139', 'website': null, 'rating': 4.6, 'reviewCount': 150, 'instagram': '@fuentesdondejulio', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Café El Aroma', 'category': 'cafeterias', 'commune': 'La Ligua', 'address': 'Av. Arturo Prat 420, La Ligua', 'lat': -32.4682, 'lon': -71.2442, 'email': null, 'phone': '+56947230770', 'website': null, 'rating': 4.5, 'reviewCount': 120, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Cafetería Doña Rosa', 'category': 'cafeterias', 'commune': 'Los Andes', 'address': 'Calle San Martín 457, Los Andes', 'lat': -32.8186, 'lon': -70.6048, 'email': 'ventas@cafeteriadonarosa.cl', 'phone': '+56322667065', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Coffee Shop Bean & Co', 'category': 'cafeterias', 'commune': 'San Felipe', 'address': 'Av. Balmaceda 494, San Felipe', 'lat': -32.7558, 'lon': -70.7265, 'email': 'hola@coffeeshopbean&co.cl', 'phone': null, 'website': 'https://coffeeshopbean&co.cl', 'rating': 3.9, 'reviewCount': 28, 'instagram': '@coffeeshopbean&co', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Pastelería Dulce Tentación', 'category': 'cafeterias', 'commune': 'Olmué', 'address': "Calle O'Higgins 531, Olmué", 'lat': -32.9919, 'lon': -71.176, 'email': null, 'phone': '+56919380372', 'website': null, 'rating': 4.7, 'reviewCount': 200, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Café Tetería Andina', 'category': 'cafeterias', 'commune': 'Valparaíso', 'address': 'Calle Esmeralda 568, Valparaíso', 'lat': -33.0493, 'lon': -71.6281, 'email': 'contacto@cafeteteriaandina.cl', 'phone': '+56338016313', 'website': null, 'rating': 3.5, 'reviewCount': 12, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Bistrot La Terraza', 'category': 'cafeterias', 'commune': 'Viña del Mar', 'address': 'Calle Valparaíso 605, Viña del Mar', 'lat': -33.0109, 'lon': -71.5408, 'email': null, 'phone': '+56939152515', 'website': 'https://www.bistrotlaterraza.cl', 'rating': 4.0, 'reviewCount': 67, 'instagram': '@bistrotlaterraza', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Café El Mirador', 'category': 'cafeterias', 'commune': 'Quilpué', 'address': 'Calle Serrano 642, Quilpué', 'lat': -33.0513, 'lon': -71.4602, 'email': 'info@cafeelmirador.cl', 'phone': '+56323179179', 'website': 'https://www.cafeelmirador.cl', 'rating': null, 'reviewCount': 0, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Cervecería Artesanal', 'category': 'bares', 'commune': 'Villa Alemana', 'address': 'Av. Libertad 679, Villa Alemana', 'lat': -32.937799999999996, 'lon': -71.3584, 'email': null, 'phone': null, 'website': null, 'rating': 4.3, 'reviewCount': 89, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Bar El Pub', 'category': 'bares', 'commune': 'Concón', 'address': 'Av. Marina 716, Concón', 'lat': -32.9191, 'lon': -71.5404, 'email': 'ventas@barelpub.cl', 'phone': '+56941983057', 'website': null, 'rating': 3.8, 'reviewCount': 5, 'instagram': '@barelpub', 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Discoteca La Cueva', 'category': 'bares', 'commune': 'Limache', 'address': 'Calle Yungay 753, Limache', 'lat': -32.9508, 'lon': -71.2707, 'email': 'hola@discotecalacueva.cl', 'phone': '+56336219085', 'website': null, 'rating': 4.6, 'reviewCount': 150, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Cantina Los Amigos', 'category': 'bares', 'commune': 'Quillota', 'address': "Calle O'Higgins 790, Quillota", 'lat': -32.899699999999996, 'lon': -71.2681, 'email': null, 'phone': '+56924350485', 'website': 'https://cantinalosamigos.cl', 'rating': 4.5, 'reviewCount': 120, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Dom 10:00-22:00'},
  {'name': 'Hostal El Viajero', 'category': 'alojamiento_turismo', 'commune': 'San Antonio', 'address': 'Calle Prat 827, San Antonio', 'lat': -33.583800000000004, 'lon': -71.6161, 'email': 'contacto@hostalelviajero.cl', 'phone': '+56324908668', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': '@hostalelviajero', 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Cabañas Los Pinos', 'category': 'alojamiento_turismo', 'commune': 'Casablanca', 'address': 'Calle San Martín 864, Casablanca', 'lat': -33.3155, 'lon': -71.3979, 'email': null, 'phone': null, 'website': null, 'rating': 3.9, 'reviewCount': 28, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Hotel Costa Brava', 'category': 'alojamiento_turismo', 'commune': 'Quintero', 'address': 'Calle Los Pescadores 901, Quintero', 'lat': -32.7523, 'lon': -71.55279999999999, 'email': 'info@hotelcostabrava.cl', 'phone': '+56924979759', 'website': 'https://www.hotelcostabrava.cl', 'rating': 4.7, 'reviewCount': 200, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Hostería El Valle', 'category': 'alojamiento_turismo', 'commune': 'La Ligua', 'address': 'Av. Los Carrera 938, La Ligua', 'lat': -32.4393, 'lon': -71.2397, 'email': null, 'phone': '+56332618433', 'website': 'https://www.hosteriaelvalle.cl', 'rating': 3.5, 'reviewCount': 12, 'instagram': '@hosteriaelvalle', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Apart Hotel Vista Mar', 'category': 'alojamiento_turismo', 'commune': 'Los Andes', 'address': 'Calle Yungay 975, Los Andes', 'lat': -32.8532, 'lon': -70.5911, 'email': 'ventas@aparthotelvistamar.cl', 'phone': '+56943920189', 'website': null, 'rating': 4.0, 'reviewCount': 67, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Dental Sonrisa', 'category': 'salud_privada', 'commune': 'San Felipe', 'address': 'Av. Valparaíso 1012, San Felipe', 'lat': -32.7497, 'lon': -70.749, 'email': 'hola@dentalsonrisa.cl', 'phone': '+56329619317', 'website': null, 'rating': null, 'reviewCount': 0, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Clínica Esperanza', 'category': 'salud_privada', 'commune': 'Olmué', 'address': 'Calle Portales 1049, Olmué', 'lat': -32.9956, 'lon': -71.19720000000001, 'email': null, 'phone': null, 'website': null, 'rating': 4.3, 'reviewCount': 89, 'instagram': '@clinicaesperanza', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Centro Médico Andes', 'category': 'salud_privada', 'commune': 'Valparaíso', 'address': 'Calle Merced 1086, Valparaíso', 'lat': -33.0253, 'lon': -71.6217, 'email': 'contacto@centromedicoandes.cl', 'phone': '+56977100987', 'website': 'https://centromedicoandes.cl', 'rating': 3.8, 'reviewCount': 5, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Kinesióloga Movimiento', 'category': 'salud_privada', 'commune': 'Viña del Mar', 'address': 'Calle Álamo 1123, Viña del Mar', 'lat': -33.0251, 'lon': -71.5673, 'email': null, 'phone': '+56333451949', 'website': null, 'rating': 4.6, 'reviewCount': 150, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Psicóloga Buen Vivir', 'category': 'salud_privada', 'commune': 'Quilpué', 'address': 'Av. Aníbal Pinto 1160, Quilpué', 'lat': -33.0577, 'lon': -71.4401, 'email': 'info@psicologabuenvivir.cl', 'phone': '+56920240310', 'website': null, 'rating': 4.5, 'reviewCount': 120, 'instagram': '@psicologabuenvivir', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Fonoaudióloga Voces', 'category': 'salud_privada', 'commune': 'Villa Alemana', 'address': 'Av. Presidente Ibáñez 1197, Villa Alemana', 'lat': -32.921, 'lon': -71.3559, 'email': null, 'phone': '+56322318787', 'website': 'https://www.fonoaudiologavoces.cl', 'rating': 4.2, 'reviewCount': 45, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Laboratorio Vida', 'category': 'salud_privada', 'commune': 'Concón', 'address': 'Av. El Recreo 1234, Concón', 'lat': -32.8996, 'lon': -71.54440000000001, 'email': 'ventas@laboratoriovida.cl', 'phone': null, 'website': 'https://www.laboratoriovida.cl', 'rating': 3.9, 'reviewCount': 28, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Farmacia Central', 'category': 'salud_privada', 'commune': 'Limache', 'address': "Calle O'Higgins 1271, Limache", 'lat': -32.9656, 'lon': -71.2624, 'email': 'hola@farmaciacentral.cl', 'phone': '+56937983555', 'website': null, 'rating': 4.7, 'reviewCount': 200, 'instagram': '@farmaciacentral', 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Academia Estudio', 'category': 'educacion', 'commune': 'Quillota', 'address': 'Calle Valparaíso 1308, Quillota', 'lat': -32.8748, 'lon': -71.254, 'email': null, 'phone': '+56335489479', 'website': null, 'rating': 3.5, 'reviewCount': 12, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Instituto Progreso', 'category': 'educacion', 'commune': 'San Antonio', 'address': 'Calle Matienzo 1345, San Antonio', 'lat': -33.5974, 'lon': -71.6231, 'email': 'contacto@institutoprogreso.cl', 'phone': '+56918653961', 'website': null, 'rating': 4.0, 'reviewCount': 67, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Escuela de Idiomas Global', 'category': 'educacion', 'commune': 'Casablanca', 'address': 'Calle Los Carrera 1382, Casablanca', 'lat': -33.313199999999995, 'lon': -71.4364, 'email': null, 'phone': '+56323342104', 'website': 'https://escueladeidiomasglob.cl', 'rating': null, 'reviewCount': 0, 'instagram': '@escueladeidiomasglob', 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Clases Matemáticas Fácil', 'category': 'educacion', 'commune': 'Quintero', 'address': 'Calle El Águila 1419, Quintero', 'lat': -32.7505, 'lon': -71.5189, 'email': 'info@clasesmatematicasfac.cl', 'phone': null, 'website': null, 'rating': 4.3, 'reviewCount': 89, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Academia de Música Sonidos', 'category': 'educacion', 'commune': 'La Ligua', 'address': 'Av. Libertad 1456, La Ligua', 'lat': -32.467200000000005, 'lon': -71.2438, 'email': null, 'phone': '+56995895305', 'website': null, 'rating': 3.8, 'reviewCount': 5, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Centro de Capacitación Labor', 'category': 'educacion', 'commune': 'Los Andes', 'address': 'Calle Lautaro 1493, Los Andes', 'lat': -32.848, 'lon': -70.5826, 'email': 'ventas@centrodecapacitacion.cl', 'phone': '+56333488749', 'website': 'https://www.centrodecapacitacion.cl', 'rating': 4.6, 'reviewCount': 150, 'instagram': '@centrodecapacitacion', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Gimnasio Power', 'category': 'gimnasios', 'commune': 'San Felipe', 'address': 'Av. Libertador 1530, San Felipe', 'lat': -32.7377, 'lon': -70.7457, 'email': 'hola@gimnasiopower.cl', 'phone': '+56922806244', 'website': 'https://www.gimnasiopower.cl', 'rating': 4.5, 'reviewCount': 120, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Centro Fitness Vital', 'category': 'gimnasios', 'commune': 'Olmué', 'address': 'Calle San Martín 67, Olmué', 'lat': -33.0036, 'lon': -71.1687, 'email': null, 'phone': '+56321627596', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'CrossFit Zona 5', 'category': 'gimnasios', 'commune': 'Valparaíso', 'address': 'Calle Condell 104, Valparaíso', 'lat': -33.026700000000005, 'lon': -71.6113, 'email': 'contacto@crossfitzona5.cl', 'phone': null, 'website': null, 'rating': 3.9, 'reviewCount': 28, 'instagram': '@crossfitzona5', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Estudio de Yoga Paz', 'category': 'gimnasios', 'commune': 'Viña del Mar', 'address': 'Calle 1 Norte 141, Viña del Mar', 'lat': -33.0402, 'lon': -71.5641, 'email': null, 'phone': '+56978835016', 'website': null, 'rating': 4.7, 'reviewCount': 200, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Pilates Core', 'category': 'gimnasios', 'commune': 'Quilpué', 'address': 'Calle Portales 178, Quilpué', 'lat': -33.06, 'lon': -71.4443, 'email': 'info@pilatescore.cl', 'phone': '+56339272604', 'website': 'https://pilatescore.cl', 'rating': 3.5, 'reviewCount': 12, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'AutoMecánica El Motor', 'category': 'automotor', 'commune': 'Villa Alemana', 'address': 'Av. El Bosque 215, Villa Alemana', 'lat': -32.9516, 'lon': -71.355, 'email': null, 'phone': '+56911252894', 'website': null, 'rating': 4.0, 'reviewCount': 67, 'instagram': '@automecanicaelmotor', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Taller Don Pedro', 'category': 'automotor', 'commune': 'Concón', 'address': 'Av. Los Pelícanos 252, Concón', 'lat': -32.9308, 'lon': -71.53160000000001, 'email': 'ventas@tallerdonpedro.cl', 'phone': '+56321603697', 'website': null, 'rating': null, 'reviewCount': 0, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Lubricentro Velocidad', 'category': 'automotor', 'commune': 'Limache', 'address': 'Calle Portales 289, Limache', 'lat': -32.971500000000006, 'lon': -71.2473, 'email': 'hola@lubricentrovelocidad.cl', 'phone': null, 'website': 'https://www.lubricentrovelocidad.cl', 'rating': 4.3, 'reviewCount': 89, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Gomera Rápida', 'category': 'automotor', 'commune': 'Quillota', 'address': 'Calle Lautaro 326, Quillota', 'lat': -32.8927, 'lon': -71.2386, 'email': null, 'phone': '+56968567307', 'website': 'https://www.gomerarapida.cl', 'rating': 3.8, 'reviewCount': 5, 'instagram': '@gomerarapida', 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Autolavado Sparkle', 'category': 'automotor', 'commune': 'San Antonio', 'address': 'Calle Los Pescadores 363, San Antonio', 'lat': -33.609300000000005, 'lon': -71.6211, 'email': 'contacto@autolavadosparkle.cl', 'phone': '+56331626138', 'website': null, 'rating': 4.6, 'reviewCount': 150, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Repuestos AutoPartes', 'category': 'automotor', 'commune': 'Casablanca', 'address': 'Calle Vicuña 400, Casablanca', 'lat': -33.334399999999995, 'lon': -71.4133, 'email': null, 'phone': '+56974970120', 'website': null, 'rating': 4.5, 'reviewCount': 120, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Boutique Moda', 'category': 'retail', 'commune': 'Quintero', 'address': 'Calle Las Gaviotas 437, Quintero', 'lat': -32.7483, 'lon': -71.5501, 'email': 'info@boutiquemoda.cl', 'phone': '+56327092113', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': '@boutiquemoda', 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Tienda De Todo', 'category': 'retail', 'commune': 'La Ligua', 'address': "Av. O'Higgins 474, La Ligua", 'lat': -32.443000000000005, 'lon': -71.2439, 'email': null, 'phone': null, 'website': 'https://tiendadetodo.cl', 'rating': 3.9, 'reviewCount': 28, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Zapatería El Paso', 'category': 'retail', 'commune': 'Los Andes', 'address': 'Calle Balmaceda 511, Los Andes', 'lat': -32.8485, 'lon': -70.58439999999999, 'email': 'ventas@zapateriaelpaso.cl', 'phone': '+56941165155', 'website': null, 'rating': 4.7, 'reviewCount': 200, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Juguetería Alegre', 'category': 'retail', 'commune': 'San Felipe', 'address': 'Av. Los Carrera 548, San Felipe', 'lat': -32.7532, 'lon': -70.73, 'email': 'hola@jugueteriaalegre.cl', 'phone': '+56333674346', 'website': null, 'rating': 3.5, 'reviewCount': 12, 'instagram': '@jugueteriaalegre', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Librería Papel y Tinta', 'category': 'retail', 'commune': 'Olmué', 'address': 'Calle Yungay 585, Olmué', 'lat': -32.9932, 'lon': -71.1907, 'email': null, 'phone': '+56943748499', 'website': 'https://www.libreriapapelytinta.cl', 'rating': 4.0, 'reviewCount': 67, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Florería Jardín', 'category': 'retail', 'commune': 'Valparaíso', 'address': 'Av. Pedro Montt 622, Valparaíso', 'lat': -33.0375, 'lon': -71.6061, 'email': 'contacto@floreriajardin.cl', 'phone': '+56325692638', 'website': 'https://www.floreriajardin.cl', 'rating': null, 'reviewCount': 0, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Tienda Natural', 'category': 'retail', 'commune': 'Viña del Mar', 'address': 'Calle San Francisco 659, Viña del Mar', 'lat': -33.0417, 'lon': -71.5633, 'email': null, 'phone': null, 'website': null, 'rating': 4.3, 'reviewCount': 89, 'instagram': '@tiendanatural', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-20:00'},
  {'name': 'Contadores Asesorías', 'category': 'servicios_profesionales', 'commune': 'Quilpué', 'address': 'Calle Manuel Rodríguez 696, Quilpué', 'lat': -33.0567, 'lon': -71.4255, 'email': 'info@contadoresasesorias.cl', 'phone': '+56918500252', 'website': null, 'rating': 3.8, 'reviewCount': 5, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Abogados Defensa', 'category': 'servicios_profesionales', 'commune': 'Villa Alemana', 'address': 'Av. Los Pinos 733, Villa Alemana', 'lat': -32.9473, 'lon': -71.3617, 'email': null, 'phone': '+56331085905', 'website': null, 'rating': 4.6, 'reviewCount': 150, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Inmobiliaria Casas', 'category': 'servicios_profesionales', 'commune': 'Concón', 'address': 'Av. Borgoño 770, Concón', 'lat': -32.9002, 'lon': -71.54690000000001, 'email': 'ventas@inmobiliariacasas.cl', 'phone': '+56927533315', 'website': 'https://inmobiliariacasas.cl', 'rating': 4.5, 'reviewCount': 120, 'instagram': '@inmobiliariacasas', 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Corredora de Propiedades Hogar', 'category': 'servicios_profesionales', 'commune': 'Limache', 'address': 'Calle San Martín 807, Limache', 'lat': -32.957, 'lon': -71.2805, 'email': 'hola@corredoradepropiedad.cl', 'phone': '+56328346617', 'website': null, 'rating': 4.2, 'reviewCount': 45, 'instagram': null, 'verifiedSignal': 'Instagram', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Diseño Gráfico Creativo', 'category': 'servicios_profesionales', 'commune': 'Quillota', 'address': 'Calle San Martín 844, Quillota', 'lat': -32.895199999999996, 'lon': -71.2446, 'email': null, 'phone': null, 'website': null, 'rating': 3.9, 'reviewCount': 28, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Estudio de Arquitectura Diseño', 'category': 'servicios_profesionales', 'commune': 'San Antonio', 'address': 'Calle San Pedro 881, San Antonio', 'lat': -33.6049, 'lon': -71.6135, 'email': 'contacto@estudiodearquitectur.cl', 'phone': '+56916251216', 'website': 'https://www.estudiodearquitectur.cl', 'rating': 4.7, 'reviewCount': 200, 'instagram': '@estudiodearquitectur', 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Sab 9:00-19:00'},
  {'name': 'Constructora Andes', 'category': 'construccion', 'commune': 'Casablanca', 'address': 'Calle Prat 918, Casablanca', 'lat': -33.3035, 'lon': -71.4349, 'email': null, 'phone': '+56337525291', 'website': 'https://www.constructoraandes.cl', 'rating': 3.5, 'reviewCount': 12, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Vie 8:00-18:00'},
  {'name': 'Maestranza El Fierro', 'category': 'construccion', 'commune': 'Quintero', 'address': 'Calle San Pedro 955, Quintero', 'lat': -32.7802, 'lon': -71.5356, 'email': 'info@maestranzaelfierro.cl', 'phone': '+56964115865', 'website': null, 'rating': 4.0, 'reviewCount': 67, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Vie 8:00-18:00'},
  {'name': 'Carpintería El Roble', 'category': 'construccion', 'commune': 'La Ligua', 'address': 'Av. Valparaíso 992, La Ligua', 'lat': -32.4322, 'lon': -71.2257, 'email': null, 'phone': '+56321367049', 'website': null, 'rating': null, 'reviewCount': 0, 'instagram': '@carpinteriaelroble', 'verifiedSignal': 'Instagram', 'hours': 'Lun-Vie 8:00-18:00'},
  {'name': 'Ferretería La Herramienta', 'category': 'construccion', 'commune': 'Los Andes', 'address': 'Calle Valparaíso 1029, Los Andes', 'lat': -32.83, 'lon': -70.6141, 'email': 'ventas@ferreterialaherramie.cl', 'phone': null, 'website': null, 'rating': 4.3, 'reviewCount': 89, 'instagram': null, 'verifiedSignal': 'Google Maps', 'hours': 'Lun-Vie 8:00-18:00'},
  {'name': 'Vidriería Cristal', 'category': 'construccion', 'commune': 'San Felipe', 'address': 'Av. Condell 1066, San Felipe', 'lat': -32.7649, 'lon': -70.741, 'email': 'hola@vidrieriacristal.cl', 'phone': '+56915686256', 'website': 'https://vidrieriacristal.cl', 'rating': 3.8, 'reviewCount': 5, 'instagram': null, 'verifiedSignal': 'LinkedIn', 'hours': 'Lun-Vie 8:00-18:00'},
];
export default { SIMULATED_BUSINESSES, SIMULATED_BUSINESSES_EXTRA };
