/**
 * =============================================================================
 *  Prospección B2B — fixtures del proveedor SIMULADO
 * -----------------------------------------------------------------------------
 *  Negocios de ejemplo con datos REALISTAS de la Quinta Región:
 *  comunas reales, categorías reales, nombres chilenos.
 *  Son datos SINTÉTICOS (no scrapeados): solo para modo simulación/demo.
 *  En producción, el descubrimiento real debe venir de fuentes con
 *  términos de uso validados (ver scraper.js — deshabilitado por defecto).
 * =============================================================================
 */

export const SIMULATED_BUSINESSES = [
  {
    name: 'Dental Sonrisa Viña',
    category: 'salud_privada',
    commune: 'Viña del Mar',
    address: 'Av. Libertad 1234, Viña del Mar',
    lat: -33.0246, lon: -71.5518,
    email: 'contacto@dentallsonrisa.cl',
    phone: '+56322981234',
    website: 'https://dentallsonrisa.cl',
    rating: 3.8, reviewCount: 42,
    instagram: '@dentallsonrisa',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 9:00-18:00',
  },
  {
    name: 'Café del Puerto',
    category: 'cafeterias',
    commune: 'Valparaíso',
    address: 'Calle Prat 456, Valparaíso',
    lat: -33.0458, lon: -71.6197,
    email: 'hola@cafedelpuerto.cl',
    phone: '+56987654321',
    website: 'https://cafedelpuerto.cl',
    rating: 4.5, reviewCount: 18,
    instagram: '@cafedelpuertovpo',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 8:00-21:00',
  },
  {
    name: 'Gimnasio IronQuilpué',
    category: 'gimnasios',
    commune: 'Quilpué',
    address: 'Av. Aníbal Pinto 789, Quilpué',
    lat: -33.0473, lon: -71.4428,
    email: 'info@ironquilpue.cl',
    phone: '+56912345678',
    website: null,
    rating: 4.1, reviewCount: 9,
    instagram: '@ironquilpue',
    verifiedSignal: 'Instagram',
    hours: 'Lun-Sab 7:00-22:00',
  },
  {
    name: 'Hostal Canela Concon',
    category: 'alojamiento_turismo',
    commune: 'Concón',
    address: 'Av. Borgoño 1500, Concón',
    lat: -32.9175, lon: -71.5310,
    email: null,
    phone: '+56998765432',
    website: 'https://hostalcanela.cl',
    rating: 3.5, reviewCount: 27,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Recepción 24h',
  },
  {
    name: 'AutoMecánica El Bosque',
    category: 'automotor',
    commune: 'Villa Alemana',
    address: 'Av. Las Acacias 321, Villa Alemana',
    lat: -32.9336, lon: -71.3750,
    email: 'contacto@automecanicaelbosque.cl',
    phone: '+56955667788',
    website: null,
    rating: null, reviewCount: 0,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 8:30-18:30',
  },
  {
    name: 'Panadería La Espiga',
    category: 'restaurantes',
    commune: 'Quillota',
    address: 'Calle O\'Higgins 210, Quillota',
    lat: -32.8833, lon: -71.2500,
    email: null,
    phone: '+56334455667',
    website: null,
    rating: 4.7, reviewCount: 3,
    instagram: '@laespigaquillota',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Dom 7:00-20:00',
  },
  {
    name: 'Clínica Veterinaria Patitas',
    category: 'salud_privada',
    commune: 'Limache',
    address: 'Av. Matta 100, Limache',
    lat: -32.9667, lon: -71.2667,
    email: 'atencion@patitasvet.cl',
    phone: '+56911223344',
    website: 'https://patitasvet.cl',
    rating: 4.2, reviewCount: 61,
    instagram: '@patitasvet',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Sab 9:00-19:00',
  },
  {
    name: 'Boutique Luna Nueva',
    category: 'retail',
    commune: 'San Antonio',
    address: 'Av. Barros Luco 55, San Antonio',
    lat: -33.5955, lon: -71.6130,
    email: 'ventas@lunanueva.cl',
    phone: '+56922334455',
    website: null,
    rating: 3.9, reviewCount: 14,
    instagram: '@lunanuevasanantonio',
    verifiedSignal: 'Instagram',
    hours: 'Lun-Sab 10:00-19:00',
  },
  {
    name: 'Constructora Andes Sur',
    category: 'construccion',
    commune: 'San Felipe',
    address: 'Av. Libertador 880, San Felipe',
    lat: -32.7500, lon: -70.7333,
    email: 'proyectos@andessur.cl',
    phone: '+56966778899',
    website: 'https://andessur.cl',
    rating: null, reviewCount: 0,
    instagram: null,
    verifiedSignal: 'LinkedIn',
    hours: 'Lun-Vie 8:00-17:00',
  },
  {
    name: 'Escuela de Danza Ritmo',
    category: 'educacion',
    commune: 'Valparaíso',
    address: 'Calle Condell 990, Valparaíso',
    lat: -33.0370, lon: -71.6230,
    email: 'inscripciones@danzaritmo.cl',
    phone: '+56944556677',
    website: 'https://danzaritmo.cl',
    rating: 4.8, reviewCount: 22,
    instagram: '@danzaritmovpo',
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 15:00-21:00',
  },
  {
    name: 'Asesorías Contables Pérez',
    category: 'servicios_profesionales',
    commune: 'Viña del Mar',
    address: 'Av. Perú 1100, Viña del Mar',
    lat: -33.0190, lon: -71.5480,
    email: 'contacto@perezcontadores.cl',
    phone: '+56988776655',
    website: null,
    rating: 4.0, reviewCount: 7,
    instagram: null,
    verifiedSignal: 'Google Maps',
    hours: 'Lun-Vie 9:00-18:00',
  },
  {
    name: 'Cervecería Artesanal Muelle',
    category: 'bares',
    commune: 'Valparaíso',
    address: 'Paseo 21 de Mayo 200, Valparaíso',
    lat: -33.0385, lon: -71.6270,
    email: null,
    phone: '+56933445566',
    website: 'https://cerveceriamuelle.cl',
    rating: 4.3, reviewCount: 150,
    instagram: '@cerveceriamuelle',
    facebook: 'cerveceriamuelle',
    verifiedSignal: 'Google Maps',
    hours: 'Mar-Dom 12:00-24:00',
  },
];

export default { SIMULATED_BUSINESSES };
